### ISSUE TITLE
Доработать роутер.

### ISSUE THREAD

**Issue by misterjt** [kulakowka/Backbone.js-Russian#12]
Роутер ну очень сырой.
Во первых метод navigate у роутера меняет URL сразу же после вызова. То есть у меня нет возможности сначала загрузить данные с сервера, и после загрузки изменить адрес. Плюс я не имею никакого контроля над передвижением по навигационным кнопкам "назад" и "вперед". Сделайте  пожалуйста по гибче, что бы я имел полный контроль над всеми действиями.

**Comment by hogart** [comment]
Это вам не сюда надо писать. Тут просто перевод документации.

**Comment by misterjt** [comment]
Я знаю что не сюда) Я просто думал отсюда добрые дяди пишут уже куда надо на английском. Я просто не знаю как перевести то, что я хочу написать им

**Comment by hogart** [comment]
Если вас не устраивает бэкбоновский роутер, выкиньте его и возьмите любой другой, их миллион.

**Comment by misterjt** [comment]
Не подскажите как правильно его выкинуть из production-версии?

**Comment by hogart** [comment]
Да просто не используйте.

**Comment by misterjt** [comment]
Жалко лишние килобайты трафика загружать. Забочусь о пользователе)

**Comment by hogart** [comment]
Берете несжатую версию, выкидываете оттуда код роутера, а о сжатии должна позаботиться ваша собственная система сжатия и сборки статики — если вы так дрожите над тремя килобайтами, наверняка она у вас есть:)

**Comment by misterjt** [comment]
Нету такой системы) Может посоветуете? Я поискал, но все, что нашел сжимает не так же, как сжат оригинальные backbone.

**Comment by hogart** [comment]
Я Grunt.js использую, меня вполне устраивает. [http://habrahabr.ru/post/148274/](несколько устаревшая статья на хабре)
